<a href="https://colab.research.google.com/github/Mahal09/Python/blob/main/Week2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The difference between the NumPy and pandas are Numpy can store only values of one datatypes as a list or array or tuple.

*   But Pandas can store different datatypes in a single dataframe as an array, tuple or list or when initialising in a dictionary.
*   Pandas can be used in more complex intializing and indexing. Accessing complex dataFrames in pandas is possible.

Answers from AI Editor

NumPy
----------
NumPy stands for "Numerical Python" and is the foundational package for numerical computing in Python. Here are some key characteristics:

Core Data Structure:
---------------------------

ndarray: The central object in NumPy is the ndarray (N-dimensional array), which is a multi-dimensional array of homogeneous data types (all elements must be of the same type).
Performance:

Speed: NumPy is highly efficient for numerical operations because it uses optimized C code under the hood.
Vectorization: Operations on ndarrays are vectorized, meaning you can apply operations on entire arrays without explicit loops, leading to faster execution.
Mathematical Functions:

Broad Range of Functions: NumPy offers a wide range of mathematical functions for linear algebra, statistics, Fourier transforms, random number generation, etc.
Usability:

Low-level Operations: NumPy is excellent for performing basic array operations and is often used as a base for other libraries (including Pandas).
-----------------------------------------------
Pandas
--------
Pandas is a high-level data manipulation tool built on top of NumPy. It provides more advanced data structures and operations designed for practical, real-world data analysis. Some key features include:

Core Data Structures:
-------------------------
Series: A one-dimensional labeled array capable of holding any data type.
DataFrame: A two-dimensional labeled data structure with columns of potentially different types, similar to a table in a database or an Excel spreadsheet.

Data Handling:

Handling Missing Data: Pandas offers robust functionality for detecting, handling, and filling missing data.
Label-based Indexing: Allows accessing and manipulating data via labels (indices) rather than just integer index positions.

Data Manipulation:

Merge, Join, and Concatenate: Provides functions for merging, joining, and concatenating datasets.
Group By: Supports grouping data and performing aggregate operations on these groups.
Time Series Analysis: Includes capabilities for dealing with time series data, such as resampling and frequency conversion.

Integration:

Excel, SQL, CSV: Easy integration with various data file formats and databases, providing functions to read from and write to these formats.

When to Use Each
Use NumPy when:

You need to perform low-level mathematical computations.
Your focus is on array operations, linear algebra, Fourier transforms, and random numbers.
You require high performance for numerical calculations.

Use Pandas when:

You need to manipulate and analyze structured data (e.g., data tables).
Your work involves handling missing data, data cleaning, and preparation.
You want to integrate seamlessly with data files like CSVs, Excel, SQL databases.

Conclusion

NumPy is invaluable for numerical computation and serves as the foundation for many other scientific computing libraries.
Pandas builds upon NumPy, offering more advanced data structures and data manipulation tools that are suited for data analysis workflows, particularly with tabular data.
Together, these libraries provide a comprehensive toolkit for handling a wide range of data analysis tasks in Python.

In [1]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
arr_str = ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']

# defining a list of number of cylinders in car or numerical elements
arr_num = [5, 4, 6, 7, 3]


In [ ]:
np_arr_str = np.array (arr_str)
np_arr_num = np.array(arr_num)

print(np_arr_str)
print(type(np_arr_num))

['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']
<class 'numpy.ndarray'>


In [ ]:
print('Data type of arr_str: ',type(arr_str))
print('Data type of arr_num: ',type(arr_num))

# printing the data type after conversion of lists to array
print('Data type of np_arr_str: ',type(np_arr_str))
print('Data type of np_arr_num: ',type(np_arr_num))

Data type of arr_str:  <class 'list'>
Data type of arr_num:  <class 'list'>
Data type of np_arr_str:  <class 'numpy.ndarray'>
Data type of np_arr_num:  <class 'numpy.ndarray'>


In [ ]:
matrix = np.array([[1,2,1],[4,5,9],[1,8,9]])
print( matrix)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [ ]:
print(type( matrix))

<class 'numpy.ndarray'>


In [ ]:
arr2  = np.arange(start = 0, stop = 10)
# 10 will be excluded from the output
print(arr2)

# or

arr2  = np.arange(0,10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr3 = np.arange(0,20,5)
print(arr3)

[ 0  5 10 15]


In [ ]:
arr3 = np.arange(0,20,5)
arr3

array([ 0,  5, 10, 15])

In [ ]:
arr3  = np.arange(start = 0, stop = 20, step = 5)
arr3

array([ 0,  5, 10, 15])

In [ ]:
matrix2 = np.linspace(0,5) # by default 50 evenly spaced values will be generated between 0 and 5
type(matrix2)
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

How are these values getting generated?

The step size or the difference between each element will be decided by the following formula:

(stop - start) / (total elements - 1)

So, in this case: (5 - 0) / 49 = 0.10204082

The first value will be 0.10204082, the second value will be 0.10204082 + 0.10204082, the third value will be 0.10204082 + 0.10204082 +0.10204082, and so on

In [ ]:
# generating 10 evenly spaced values between 10 and 20
matrix3 = np.linspace(10,20,11)
matrix3

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

20-10/11-1 =10/10

In [ ]:
matrix4 = np.zeros([3,5])
matrix4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
matrix4 = np.zeros([3,15])
matrix4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
matrix5 = np.ones([3,7])
matrix5

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
matrix5 = np.ones([2,2])
matrix5

array([[1., 1.],
       [1., 1.]])

In [ ]:
# prompt: what is the use of Using np.eye()

import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

# Explanation:
# np.eye(n) creates an n x n identity matrix.
# An identity matrix has 1s on the main diagonal and 0s everywhere else.
# It's useful for linear algebra operations and matrix transformations.


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
matrix6 = np.eye(4)
print(matrix6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
vec = np.zeros([2,3])
print(vec)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
vec = np.linspace(10,20,3)
vec1 = np.linspace(20,40,2)
print(vec1)

print(vec+vec1)

[20. 40.]


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
arr4 = np.arange(0,10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr4_reshaped = arr4.reshape(2,5)
arr4_reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr5 = np.array([10,2,6])
np.exp(arr5)

array([2.20264658e+04, 7.38905610e+00, 4.03428793e+02])

In [ ]:
print('Sine function',np.sin(30))

print('Cosine function',np.cos(30))
print('Tan Function',np.tan(60))


Sine function -0.9880316240928618
Cosine function 0.15425144988758405
Tan Function 0.320040389379563


In [ ]:
# prompt: why everything in np comes with more floating point numbers

# NumPy often uses floating-point numbers because it's the default for many mathematical operations.
# This is due to the nature of numerical computing and the way NumPy is designed to handle various mathematical functions and operations efficiently.

# Here's why:

# 1.  Mathematical Functions: Many mathematical functions in NumPy (like trigonometric functions, logarithms, etc.) are defined for floating-point numbers. Using floating-point numbers allows for a wider range of values and more precise calculations.

# 2.  Compatibility with Other Libraries:  Floating-point numbers are the standard for scientific computing and data analysis.  This ensures compatibility with other libraries and tools that rely on floating-point numbers.

# 3.  Efficiency: Floating-point operations are highly optimized in hardware and software, making computations faster.

# 4.  Precision: While integers are suitable for discrete values, floating-point numbers offer greater precision for representing real-world data and calculations involving decimals.


# To illustrate this, let's look at an example:
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64

arr = np.array([1, 2, 3], dtype=float)
print(arr.dtype)  # Output: float64

# As you can see, by default, NumPy might infer the data type as int64. However, you can explicitly specify the data type as float64 if needed.


In [ ]:
# prompt: np.exp(2) , how and why

import numpy as np

result = np.exp(2)
print(result)

# Explanation:
# np.exp(2) calculates the exponential value of 2.
# It means e raised to the power of 2, where 'e' is the base of the natural logarithm (approximately 2.71828).
# The result will be approximately 7.38905609893065.


In [ ]:
np.log(arr5)

array([2.30258509, 0.69314718, 1.79175947])

In [ ]:
np.log10(8)

0.9030899869919435

In [ ]:
np.log(2)

0.6931471805599453

In [ ]:
vec1 = np.arange(0,12)
print(vec1)
vec2 = vec1.reshape(2,6)
print(vec2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
vec = np.arange(0,5)
print(vec)
print(vec.reshape(1,5))

[0 1 2 3 4]
[[0 1 2 3 4]]


In [ ]:
l1 = [1,2,3]
l2 = [4,5,6]
print(l1+l2)

[1, 2, 3, 4, 5, 6]


In [ ]:
arr7 = np.arange(1,6)
print('arr7:',arr7)

arr8 = np.arange(3,8)
print('arr8:',arr8)

arr7: [1 2 3 4 5]
arr8: [3 4 5 6 7]


In [ ]:
print('Addition: ',arr7+arr8)
print('Subtraction: ',arr8-arr7)
print('Multiplication:' , arr7*arr8)
print('Division:', arr7/arr8)
print('Inverse:', 1/arr7)
print('Powers:', arr7**arr8) # in python, powers are achieved using **, NOT ^!!! ^ does something completely different!

Addition:  [ 4  6  8 10 12]
Subtraction:  [2 2 2 2 2]
Multiplication: [ 3  8 15 24 35]
Division: [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse: [1.         0.5        0.33333333 0.25       0.2       ]
Powers: [    1    16   243  4096 78125]


In [ ]:
matrix7 =np.arange(1,10).reshape(3,3)
print(matrix7)
matrix8 = np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print('Addition transpose: \n',np.transpose(matrix7+matrix8))
print('addition: \n', matrix7+matrix8)
print('Subtraction: \n ', matrix7-matrix8)
print('Multiplication: \n', matrix7*matrix8)
print('Division: \n', matrix7/matrix8)

Addition transpose: 
 [[ 2.  4.  7.]
 [ 2.  6.  8.]
 [ 3.  6. 10.]]
addition: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Subtraction: 
  [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division: 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


<ipython-input-69-acded3ad6175>:5: RuntimeWarning: divide by zero encountered in divide
  print('Division: \n', matrix7/matrix8)


In [ ]:
matrix7 = np.arange(1,10).reshape(3,3)
print(matrix7)

matrix8 = np.eye(3)
print(matrix8)

In [ ]:
veec = np.arange(2,5,1)
print(1/veec)
print(veec**2)

[0.5        0.33333333 0.25      ]
[ 4  9 16]


In [ ]:
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.eye(2)
print(mat1/mat2)

[[ 1. inf]
 [inf  4.]]


<ipython-input-84-0e6adcba2ca7>:3: RuntimeWarning: divide by zero encountered in divide
  print(mat1/mat2)


In [ ]:
0.25*2

0.5

In [ ]:
0.5*2

1.0

In [ ]:
rand_mat = np.random.randn(5)
print(rand_mat)

[-0.18573995  0.2154751   0.23664706  0.46837086 -0.30108808]


In [ ]:
rand_mat2 = np.random.rand(5)
print(rand_mat2)

[0.22803719 0.98893504 0.68396906 0.7979226  0.11277643]


In [ ]:
rand_mat = np.random.randn(5,5)
print(rand_mat)

[[ 0.1527305   1.10241297 -0.06482158 -0.72423698  1.32944484]
 [ 0.19751992 -0.54389682 -0.4049916  -2.23888652 -2.19089248]
 [-0.60097248  0.74918037 -0.93624118 -0.71758916 -0.0912532 ]
 [ 0.23619711 -0.13290724 -1.1624427  -0.43542412 -1.299046  ]
 [-0.63402732  1.07610857 -0.85721652 -2.68582467 -0.53857891]]


In [ ]:
print(np.mean(rand_mat2))
print(np.std(rand_mat2))

0.5623280613964007
0.33649424648743237


In [4]:
rand_mat3=np.random.randint(1,5,10)
print(rand_mat3)

[3 2 4 4 2 3 4 1 3 3]


In [5]:
rand_mat3=np.random.randint(1,10,[5,5])
print(rand_mat3)

[[3 8 2 7 5]
 [8 6 7 4 1]
 [9 5 9 6 6]
 [1 9 9 5 9]
 [7 4 8 7 1]]


In [ ]:
mat1 = np.arange(-9,0,1).reshape(3,3)
print(mat1)
print(np.min(mat1))
print(np.max(mat1))

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
-9
-1


In [ ]:
rand_arr = np.random.randn(10)
print(rand_arr)

[-0.85963106 -0.18092958  0.67766152  1.1387774  -1.00989886 -1.11470844
 -1.88615618 -0.9415078   0.1923508   0.88548301]


In [ ]:
print(rand_arr[6])

0.9359749929087581


In [ ]:
print(rand_arr[4:9])

[-0.88759036  0.46493157  0.93597499 -0.67094174  1.4345913 ]


In [ ]:
print('Index of values to access: ',np.arange(3,10,3))
print(rand_arr[np.arange(3,10,3)])

Index of values to access:  [3 6 9]
[-0.15694803  0.93597499 -0.59469591]


In [ ]:
print(rand_arr)

[ 0.51965182 -0.54848652  0.93328396 -0.15694803 -0.88759036  0.46493157
  0.93597499 -0.67094174  1.4345913  -0.59469591]


In [ ]:
rand_arr>0

array([ True, False,  True, False, False,  True,  True, False,  True,
       False])

In [ ]:
rand_arr < 0

array([False,  True, False,  True,  True, False, False,  True, False,
        True])

In [ ]:
# prompt: what is rand and randn

# np.random.rand(n) generates an array of n random numbers uniformly distributed between 0 and 1.
# Example:
rand_mat2 = np.random.rand(5)
print(rand_mat2)

# np.random.randn(n) generates an array of n random numbers from the standard normal distribution (mean 0, variance 1).
# Example:
rand_mat = np.random.randn(5)
print(rand_mat)


[0.77779466 0.33742638 0.88135179 0.87037203 0.45493473]
[ 1.24646011 -0.67627726  0.52810239  0.77669637  0.53859691]


In [ ]:
rand_mat = np.random.randn(5,5)
print(rand_mat)

[[-0.61256465  3.01948589  1.62897345 -0.02786428 -0.64398957]
 [ 0.00701759  1.8255322  -0.25623488  1.39796888  2.0065455 ]
 [-1.54025889  0.25422903 -1.34589915  0.5359942  -0.74825582]
 [-0.77858219 -1.59906044  1.44702477  1.34960827  0.11078514]
 [ 0.72174153 -0.68999413  0.69589443 -0.3879187  -0.78007918]]


In [ ]:
rand_mat[1]

array([ 0.00701759,  1.8255322 , -0.25623488,  1.39796888,  2.0065455 ])

In [ ]:
print(rand_mat[1][2])

-0.25623488365068314


In [ ]:
print(rand_mat[0:2,1:3])

[[ 3.01948589  1.62897345]
 [ 1.8255322  -0.25623488]]


In [ ]:
print(rand_mat)

[[-0.61256465  3.01948589  1.62897345 -0.02786428 -0.64398957]
 [ 0.00701759  1.8255322  -0.25623488  1.39796888  2.0065455 ]
 [-1.54025889  0.25422903 -1.34589915  0.5359942  -0.74825582]
 [-0.77858219 -1.59906044  1.44702477  1.34960827  0.11078514]
 [ 0.72174153 -0.68999413  0.69589443 -0.3879187  -0.78007918]]


In [ ]:
print([rand_mat >0])

[array([[False,  True,  True, False, False],
       [ True,  True, False,  True,  True],
       [False,  True, False,  True, False],
       [False, False,  True,  True,  True],
       [ True, False,  True, False, False]])]


In [ ]:
print([rand_mat<0])

[array([[ True, False, False,  True,  True],
       [False, False,  True, False, False],
       [ True, False,  True, False,  True],
       [ True,  True, False, False, False],
       [False,  True, False,  True,  True]])]


In [ ]:
print(rand_mat[rand_mat>0])

[3.01948589 1.62897345 0.00701759 1.8255322  1.39796888 2.0065455
 0.25422903 0.5359942  1.44702477 1.34960827 0.11078514 0.72174153
 0.69589443]


In [ ]:
print(rand_arr)

[-0.85963106 -0.18092958  0.67766152  1.1387774  -1.00989886 -1.11470844
 -1.88615618 -0.9415078   0.1923508   0.88548301]


In [ ]:
rand_arr[5] =9
print(rand_arr)

[-0.85963106 -0.18092958  0.67766152  1.1387774  -1.00989886  9.
 -1.88615618 -0.9415078   0.1923508   0.88548301]


In [ ]:
rand_arr[2:4] = 5
print(rand_arr)

[-0.85963106 -0.18092958  5.          5.         -1.00989886  9.
 -1.88615618 -0.9415078   0.1923508   0.88548301]


In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])

5


In [6]:
print(rand_mat3)

[[3 8 2 7 5]
 [8 6 7 4 1]
 [9 5 9 6 6]
 [1 9 9 5 9]
 [7 4 8 7 1]]


# changing the values of the 4th and 5th element of the second and third rows of the matrix to 0

In [7]:
print('Matrix before modification: \n',rand_mat3)
rand_mat3[1:3,3:5] = 0
print('Matrix after modification: \n',rand_mat3)

Matrix before modification: 
 [[3 8 2 7 5]
 [8 6 7 4 1]
 [9 5 9 6 6]
 [1 9 9 5 9]
 [7 4 8 7 1]]
Matrix after modification: 
 [[3 8 2 7 5]
 [8 6 7 0 0]
 [9 5 9 0 0]
 [1 9 9 5 9]
 [7 4 8 7 1]]


In [8]:
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]


STARTING PANDAS FROM THIS, BELOW ARE THE EXAMPLES OF PANDAS ANDTHEIR FUNCTIONS.

**PANDAS**# New Section

In [11]:
# creating a list of price of different medicines
med_price_list = [55,25,45,70,90]

# converting the med_price_list to an array
med_price_arr = np.array(med_price_list)
#print(med_price_arr)

# converting the list and array into a Pandas Series object
series_list = pd.Series(med_price_list)
print(series_list)
series_arr = pd.Series(med_price_list)
print(series_arr)

0    55
1    25
2    45
3    70
4    90
dtype: int64
0    55
1    25
2    45
3    70
4    90
dtype: int64


In [17]:
med_price_list_labeled = pd.Series(med_price_list, index = ['Omeprazole','Azithromycin','Metformin','Ibuprofen','Cetirizine'])
print(med_price_list_labeled)

Omeprazole      55
Azithromycin    25
Metformin       45
Ibuprofen       70
Cetirizine      90
dtype: int64


In [18]:
med_price_list_labeled_updated = med_price_list_labeled + 2.5
print(med_price_list_labeled_updated)

Omeprazole      57.5
Azithromycin    27.5
Metformin       47.5
Ibuprofen       72.5
Cetirizine      92.5
dtype: float64


In [19]:
new_price_list = [77, 45.5, 100, 50, 80]
new_price_list_labeled = pd.Series(new_price_list, index = ['Omeprazole','Azithromycin','Metformin','Ibuprofen','Cetirizine'])
print(new_price_list_labeled)

Omeprazole       77.0
Azithromycin     45.5
Metformin       100.0
Ibuprofen        50.0
Cetirizine       80.0
dtype: float64


In [26]:
vec = np.zeros([2,3])
print(vec)


array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# prompt: why there is difference of output when the output is printed with and without print statement when vec = np.zeros([2,3])
# print(vec)

vec = np.zeros([2,3])
print(vec)
vec


[[0. 0. 0.]
 [0. 0. 0.]]


array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
matrix4 = np.zeros([3,5])
matrix4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
print('Difference between new price and old price - ')
print(new_price_list_labeled - med_price_list_labeled_updated)

Difference between new price and old price - 
Omeprazole      19.5
Azithromycin    18.0
Metformin       52.5
Ibuprofen      -22.5
Cetirizine     -12.5
dtype: float64


In [32]:
student = ['Mary', 'Peter', 'Susan', 'Toby', 'Vishal']
df1 = pd.DataFrame(student, columns =['Student'])
df1

Student
0    Mary
1   Peter
2   Susan
3    Toby
4  Vishal

In [36]:
grades = ['B','A+','A','B+','C']
cumulative_grades = ['A','B','A+','B','B']
df2 = pd.DataFrame({ 'Student': student,'Grades' : grades,'Cumulative_grades':cumulative_grades})
df2

Student Grades Cumulative_grades
0    Mary      B                 A
1   Peter     A+                 B
2   Susan      A                A+
3    Toby     B+                 B
4  Vishal      C                 B



What difference both the below statements make ? Both are storing the values in array only right ? Does Series is necessary here ?
First statement
grades = ['B','A+','A','B+','C']

another statement :

year = pd.Series([2012,2013,2014,2015,2016,2017,2018])
energy_consumption = pd.Series([2152,2196,2217,2194,2172,2180,2258])

Great question! Let's break down the statements again and examine their differences, particularly focusing on whether a Series is necessary or if a simple list (array) would suffice.

### First Statement:
```python
grades = ['B','A+','A','B+','C']
```
Here, we are using a plain Python list to store grade values. A Python list is a basic container that can hold a collection of items, and it allows for simple operations like indexing, adding, removing, and sorting items.

### Another Statement:
```python
year = pd.Series([2012,2013,2014,2015,2016,2017,2018])
energy_consumption = pd.Series([2152,2196,2217,2194,2172,2180,2258])
```
In this statement, we are creating two Pandas Series objects to store values related to years and energy consumption. A Pandas Series is a one-dimensional labeled array capable of holding any data type. It provides additional functionality over plain lists:

1. **Indexing with Labels**:
   - Each element in a Series can have an associated label, which allows for more intuitive data manipulation.
   
2. **DataFrame Integration**:
   - Series can be easily integrated into Pandas DataFrames, which are powerful data structures for data analysis and manipulation.

3. **Enhanced Functionality**:
   - Series and DataFrames come with a wide range of built-in functions for data analysis, making operations like statistical analysis and data cleaning more convenient.

### Comparison:
1. **Data Structure**:
   - **Grades List**: A simple list for storing grades. Appropriate for storing a sequence of items without needing additional features.
   - **Series Objects**: More sophisticated data structures with labels, enabling more complex operations and integrations.

2. **Usage and Necessity**:
   - **Grades List**: Sufficient for simple storage and retrieval tasks.
   - **Series**: Especially useful if you need to perform operations where data association (like linking years and energy values) or more complex data manipulation is needed.

### Is Series Necessary Here?
- **Grades**: For simply storing grades, a list can suffice unless you need to label each grade or integrate it into a DataFrame.
- **Year and Energy Consumption**: Using Series could be necessary or at least highly beneficial if you plan to perform operations like statistical analysis, plotting, or integrating with other labeled data. It provides capabilities far beyond a list, like automatic alignment during computations, handling missing values more efficiently, and more.

### Conclusion:
While both a Python list and a Pandas Series can store values in an array-like structure, Series offer enhanced functionality that is extremely valuable for data analysis tasks. In the case of storing grades, a list might suffice for basic needs. However, for storing and manipulating data such as years and energy consumption values where you might need indexing, labeling, statistical analysis, or compatibility with DataFrame structures, using a Series is indeed beneficial.

In [37]:
year = pd.Series([2012,2013,2014,2015,2016,2017,2018])
energy_consumption = pd.Series([2152,2196,2217,2194,2172,2180,2258])

df3 = pd.DataFrame({'Year':year,'Energy_Consumption(Mtoe)':energy_consumption})
df3

Year  Energy_Consumption(Mtoe)
0  2012                      2152
1  2013                      2196
2  2014                      2217
3  2015                      2194
4  2016                      2172
5  2017                      2180
6  2018                      2258

In [39]:
year = pd.Series([2012,2013,2014,2015,2016,2017,2018])
energy_consumption = pd.Series([2152,2192,2217,2194,2172,2180,2258])

df3 = pd.DataFrame({'Year': year,'Energy_Consumption(Mtoe)': energy_consumption})
df3

Year  Energy_Consumption(Mtoe)
0  2012                      2152
1  2013                      2192
2  2014                      2217
3  2015                      2194
4  2016                      2172
5  2017                      2180
6  2018                      2258

In [41]:
df4 = pd.DataFrame(np.random.randn(5,2),columns = ['Trial 1', 'Trial 2'])
df4

Trial 1   Trial 2
0  0.996440  0.215691
1 -0.217111  0.242224
2 -1.094344 -0.135375
3 -0.297484 -0.098121
4 -0.442479 -0.793029

In [43]:
operators = ['AT&T', 'Verizon', 'T-Mobile US', 'US Cellular']
revenue = [171.76, 128.29, 68.4, 4.04]

telecom = pd.Series(revenue,index = operators)
print(telecom)

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
US Cellular      4.04
dtype: float64


In [44]:
print(telecom[0])

171.76


<ipython-input-44-b5034309e53f>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(telecom[0])


In [49]:
telecom[-2:]

T-Mobile US    68.40
US Cellular     4.04
dtype: float64

In [47]:
telecom[3:]

US Cellular    4.04
dtype: float64

In [48]:
telecom[ :2]

AT&T       171.76
Verizon    128.29
dtype: float64

In [50]:
telecom[[0,2,3]]

<ipython-input-50-f444878ab99e>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  telecom[[0,2,3]]


AT&T           171.76
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

In [52]:
telecom[:'US Cellular']

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

In [56]:
telecom[['AT&T','US Cellular','Verizon']]

AT&T           171.76
US Cellular      4.04
Verizon        128.29
dtype: float64

In [64]:
day = ['day1', 'day2', 'day3', 'day4']
temperature = [31, 28, 30, 32] #temperature in degree Celsius
temp_data = pd.Series(temperature, index=day)
temp_data[2:]

day3    30
day4    32
dtype: int64

In [65]:
# creating the dataframe using dictionary
store_data = pd.DataFrame({'CustomerID': ['CustID00','CustID01','CustID02','CustID03','CustID04']
                           ,'location': ['Chicago', 'Boston', 'Seattle', 'San Francisco', 'Austin']
                           ,'gender': ['M','M','F','M','F']
                           ,'type': ['Electronics','Food&Beverages','Food&Beverages','Medicine','Beauty']
                           ,'quantity':[1,3,4,2,1],'total_bill':[100,75,125,50,80]})
store_data

CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

In [66]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data[:2]

day  calories  duration_min
0  day1       450            30
1  day2       300            25

In [68]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data['calories']

0    450
1    300
2    345
3    520
4    600
Name: calories, dtype: int64

In [69]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data

day  calories  duration_min
0  day1       450            30
1  day2       300            25
2  day3       345            29
3  day4       520            39
4  day5       600            48

In [70]:
calorie_data[::2]

day  calories  duration_min
0  day1       450            30
2  day3       345            29
4  day5       600            48

In [71]:
calorie_data[::-2]

day  calories  duration_min
4  day5       600            48
2  day3       345            29
0  day1       450            30

In [72]:
# creating the dataframe using dictionary
store_data = pd.DataFrame({'CustomerID': ['CustID00','CustID01','CustID02','CustID03','CustID04']
                           ,'location': ['Chicago', 'Boston', 'Seattle', 'San Francisco', 'Austin']
                           ,'gender': ['M','M','F','M','F']
                           ,'type': ['Electronics','Food&Beverages','Food&Beverages','Medicine','Beauty']
                           ,'quantity':[1,3,4,2,1],'total_bill':[100,75,125,50,80]})
store_data

CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

LOC USES THE NAMES OF THE COLUMNS,

ILOC USES THE NUMBERS OF THE COLUMNS.

In [75]:
store_data.loc[[1,4],['location','type']]

location            type
1   Boston  Food&Beverages
4   Austin          Beauty

In [77]:
store_data.iloc[[1,4],[0,2]]

CustomerID gender
1   CustID01      M
4   CustID04      F

In [78]:
print(store_data.loc[4,'type'])


Beauty


In [ ]:
# prompt: in this statement, which is row and column print(store_data.loc[4,'type'])

# In the statement print(store_data.loc[4,'type']):

# - 4 represents the row index (specifically, the row with index 4).
# - 'type' represents the column name.

# So, it's accessing the value in the 'type' column of the row with index 4.


In [82]:
store_data.iloc[4,3] = 'Electoronics'
store_data

CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F    Electoronics         1          80

In [83]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data

day  calories  duration_min
0  day1       450            30
1  day2       300            25
2  day3       345            29
3  day4       520            39
4  day5       600            48

In [86]:
calorie_data.iloc[0]

day             day1
calories         450
duration_min      30
Name: 0, dtype: object

In [87]:
store_data['quantity']>1

0    False
1     True
2     True
3     True
4    False
Name: quantity, dtype: bool

In [91]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data.iloc[[1,2],[1]]

calories
1       300
2       345

from matplotlib import pyplot as plt
_df_0['calories'].plot(kind='hist', bins=20, title='calories')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['calories']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'calories'}, axis=1)
              .sort_values('calories', ascending=True))
  xs = counted['calories']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_1.sort_values('calories', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('calories')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_2['calories'].plot(kind='line', figsize=(8, 4), title='calories')
plt.gca().spines[['top', 'right']].set_visible(False)

In [92]:
store_data

CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F    Electoronics         1          80

In [95]:
store_data.loc[store_data['quantity'] >1]

CustomerID       location gender            type  quantity  total_bill
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50

In [97]:
store_data['quantity']>1

0    False
1     True
2     True
3     True
4    False
Name: quantity, dtype: bool

In [98]:
rating = [1,2,3,4,5]
store_data['Rating'] = rating
store_data


CustomerID       location gender            type  quantity  total_bill  \
0   CustID00        Chicago      M     Electronics         1         100   
1   CustID01         Boston      M  Food&Beverages         3          75   
2   CustID02        Seattle      F  Food&Beverages         4         125   
3   CustID03  San Francisco      M        Medicine         2          50   
4   CustID04         Austin      F    Electoronics         1          80   

   Rating  
0       1  
1       2  
2       3  
3       4  
4       5

In [ ]:
# prompt: how to add a row in table using dict

new_row = {'CustomerID': 'CustID05', 'location': 'New York', 'gender': 'M', 'type': 'Books', 'quantity': 2, 'total_bill': 60, 'Rating': 4}
store_data = pd.concat([store_data, pd.DataFrame([new_row])], ignore_index=True)
print(store_data)


In [99]:
store_data_copy = store_data.copy()
store_data_copy

CustomerID       location gender            type  quantity  total_bill  \
0   CustID00        Chicago      M     Electronics         1         100   
1   CustID01         Boston      M  Food&Beverages         3          75   
2   CustID02        Seattle      F  Food&Beverages         4         125   
3   CustID03  San Francisco      M        Medicine         2          50   
4   CustID04         Austin      F    Electoronics         1          80   

   Rating  
0       1  
1       2  
2       3  
3       4  
4       5

In [109]:
store_data.drop(['quantity','Rating'],axis = 1,inplace = True)
store_data

CustomerID       location gender  total_bill
0   CustID00        Chicago      M         100
1   CustID01         Boston      M          75
2   CustID02        Seattle      F         125
3   CustID03  San Francisco      M          50
4   CustID04         Austin      F          80

In [105]:
store_data

CustomerID       location gender            type  quantity  total_bill  \
0   CustID00        Chicago      M     Electronics         1         100   
1   CustID01         Boston      M  Food&Beverages         3          75   
2   CustID02        Seattle      F  Food&Beverages         4         125   
3   CustID03  San Francisco      M        Medicine         2          50   
4   CustID04         Austin      F    Electoronics         1          80   

   Rating  
0       1  
1       2  
2       3  
3       4  
4       5

In [110]:
store_data.drop(2,axis =0)

CustomerID       location gender  total_bill
0   CustID00        Chicago      M         100
1   CustID01         Boston      M          75
3   CustID03  San Francisco      M          50
4   CustID04         Austin      F          80

In [111]:
store_data

CustomerID       location gender  total_bill
0   CustID00        Chicago      M         100
1   CustID01         Boston      M          75
2   CustID02        Seattle      F         125
3   CustID03  San Francisco      M          50
4   CustID04         Austin      F          80

In [117]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data[calorie_data['calories']>500]

day  calories  duration_min
3  day4       520            39
4  day5       600            48

In [118]:
calorie_data.drop('duration_min',axis =1)

day  calories
0  day1       450
1  day2       300
2  day3       345
3  day4       520
4  day5       600

In [119]:
# creating a new dataframe
store_data_new  = store_data.drop(1,axis=0)
store_data_new

CustomerID       location gender  total_bill
0   CustID00        Chicago      M         100
2   CustID02        Seattle      F         125
3   CustID03  San Francisco      M          50
4   CustID04         Austin      F          80

In [120]:
store_data_new.reset_index()

index CustomerID       location gender  total_bill
0      0   CustID00        Chicago      M         100
1      2   CustID02        Seattle      F         125
2      3   CustID03  San Francisco      M          50
3      4   CustID04         Austin      F          80

In [121]:
store_data_new.reset_index(drop=True,inplace=True)
store_data_new

CustomerID       location gender  total_bill
0   CustID00        Chicago      M         100
1   CustID02        Seattle      F         125
2   CustID03  San Francisco      M          50
3   CustID04         Austin      F          80

In [2]:
data_cust = pd.DataFrame({'customerID':['101','102','103','104'],
                        'category': ['Medium','Medium','High','Low'],
                        'first_visit': ['yes','no','yes','yes'],
                        'sales': [123,52,214,663]},index=[0,1,2,3])

data_cust_new = pd.DataFrame({'customerID':['101','103','104','105'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])

In [3]:
data_cust

customerID category first_visit  sales
0        101   Medium         yes    123
1        102   Medium          no     52
2        103     High         yes    214
3        104      Low         yes    663

In [4]:
data_cust_new

customerID  distance  sales
4        101        12    123
5        103         9    214
6        104        44    663
7        105        21    331


**Points to note while doing concat**

f1 = pd.concat([series1,series2],axis=1)
Statement: After executing the above code, either series1 will stack on top of series2 or series2 will stack on top of series1.

True

You Selected
False

Correct Option
None of the series will be on top of each other. Because the series will be combined side-by-side. When axis=0, two series will stack on each other. When axis=1, two series will stack parallel to each

In [5]:
pd.concat([data_cust,data_cust_new],axis=1)

customerID category first_visit  sales customerID  distance  sales
0        101   Medium         yes  123.0        NaN       NaN    NaN
1        102   Medium          no   52.0        NaN       NaN    NaN
2        103     High         yes  214.0        NaN       NaN    NaN
3        104      Low         yes  663.0        NaN       NaN    NaN
4        NaN      NaN         NaN    NaN        101      12.0  123.0
5        NaN      NaN         NaN    NaN        103       9.0  214.0
6        NaN      NaN         NaN    NaN        104      44.0  663.0
7        NaN      NaN         NaN    NaN        105      21.0  331.0

In [6]:
pd.concat([data_cust,data_cust_new])

customerID category first_visit  sales  distance
0        101   Medium         yes    123       NaN
1        102   Medium          no     52       NaN
2        103     High         yes    214       NaN
3        104      Low         yes    663       NaN
4        101      NaN         NaN    123      12.0
5        103      NaN         NaN    214       9.0
6        104      NaN         NaN    663      44.0
7        105      NaN         NaN    331      21.0

In [7]:
pd.merge(data_cust,data_cust_new,on='customerID',how='inner')

customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes      123        12      123
1        103     High         yes      214         9      214
2        104      Low         yes      663        44      663

In [8]:
pd.merge(data_cust,data_cust_new,on='customerID',how='outer')

customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes    123.0      12.0    123.0
1        102   Medium          no     52.0       NaN      NaN
2        103     High         yes    214.0       9.0    214.0
3        104      Low         yes    663.0      44.0    663.0
4        105      NaN         NaN      NaN      21.0    331.0

In [11]:
pd.merge(data_cust,data_cust_new,on='customerID',how='right')

customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes    123.0        12      123
1        103     High         yes    214.0         9      214
2        104      Low         yes    663.0        44      663
3        105      NaN         NaN      NaN        21      331

In [17]:
data_quaters=pd.DataFrame({'Q1':[101,102,103],'Q2':[201,202,203]},index=['I0','I1','I3'])
data_quaters
data_quaters_new = pd.DataFrame({'Q3':[301,302,303],'Q4':[401,402,403]},index = ['I0','I2','I3'])
data_quaters_new

Q3   Q4
I0  301  401
I2  302  402
I3  303  403

In [19]:
data_quaters.join(data_quaters_new,how='outer')

Q1     Q2     Q3     Q4
I0  101.0  201.0  301.0  401.0
I1  102.0  202.0    NaN    NaN
I2    NaN    NaN  302.0  402.0
I3  103.0  203.0  303.0  403.0

In [20]:
data_quaters.join(data_quaters_new,how='inner')

Q1   Q2   Q3   Q4
I0  101  201  301  401
I3  103  203  303  403

In [22]:
data_quaters.join(data_quaters_new,how='left')

Q1   Q2     Q3     Q4
I0  101  201  301.0  401.0
I1  102  202    NaN    NaN
I3  103  203  303.0  403.0

In [33]:
data_customer = pd.DataFrame({
    'customer': [101, 102, 103, 104],
    'category': ['cat2', 'cat2', 'cat1', 'cat3'],
    'important': ['yes', 'no', 'yes', 'yes'],
    'sales': [123, 52, 214, 663]
})

# Group by 'category' and count the occurrences of each 'customer'
category_customer_counts = data_customer['category'].value_counts()

# Print the result
print(category_customer_counts)

category
cat2    2
cat1    1
cat3    1
Name: count, dtype: int64
